version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/graphql-typescript
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn

      - run:
          name: Test
          command: yarn test

      - run:
          name: Report Coverage
          command: $(yarn bin)/coveralls < ./.coverage/lcov.info

      - run:
          name: Build
          command: yarn build